#!/usr/bin/env bash
# Usage: esv passwd [site] [user]
# Summary:
# Help: TBA
#

set -e

# provide sub completions
if [ "$1" == "--complete" ]; then
    if [ -n "$(type -t workon)" ] && [ "$(type -t workon)" = "function" ]; then
        $(workon)
    fi
    exit
fi

if [[ "$(hostname)" != "dev" ]]; then
    echo "Must be run on a dev server"
    exit
fi

if [ $# -lt 1  ]; then
    echo "Must specify a site to runserver"
    exit
fi

site="$1"

if [ $site != *_dev ]; then
    site="${site}_dev"
fi
user=${2:-$ESV_USERNAME}

if [[ -z $user ]]; then
    echo "Must specify a user"
    exit
fi


echo "Activating virtual environment for $site"

. `which virtualenvwrapper.sh`
workon $site && # without the && the script will exit here, not sure why

echo "Starting server on port ${port}"
python $PROJECT_ROOT/src/manage.py changepassword $user
